[package]
name = "adder-core"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3"
html2text = "0.6"
reqwest = { version = "0.11", features = ["json"] }
rss = "2.0"
serde = { version = "1.0", features = ["derive"] }
bytes = "1.0"


