version: '3'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: adder
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    networks:
      - mynet
      
networks:
  mynet:
    driver: bridge